# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PracticalTask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PracticalTask
   pod 'IQKeyboardManagerSwift'
   pod 'SwiftyJSON'
   pod 'Alamofire'
   pod 'AlamofireSwiftyJSON'
   pod 'SVProgressHUD'
   pod 'SDWebImage'
   pod 'ObjectMapper'
#   pod 'Socket.IO-Client-Swift'

    pod 'Socket.IO-Client-Swift'

  target 'PracticalTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
